/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BIL481_project;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;



import java.util.ArrayList;
import java.util.Arrays;


class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
              
     
    }
    @Test
        public void testFound() throws Exception {
           ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
           assertEquals(2, App.recursiveBinarySearch(array, 1, 4, 3));
         }
     
         @Test
         public void testNotFound() throws Exception {
           ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
           assertNotEquals(3, App.recursiveBinarySearch(array, 1, 4, 3));
         }
     
         @Test
         public void testEmptyArray() throws Exception {
           ArrayList<Integer> array = new ArrayList<>();
           assertThrows(IllegalArgumentException.class, () -> { App.recursiveBinarySearch(array, 1, 4, 3);});

         }
     
         @Test
         public void testNull() throws Exception {
          assertThrows(NullPointerException.class, () -> { App.recursiveBinarySearch(null, 1, 4, 3);});
         }
         @Test
         public void testCompareBoundries() throws Exception {
          ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
          assertThrows(IllegalArgumentException.class, () -> { App.recursiveBinarySearch(array, 4, 1, 3);});
         }
}
